Created Telegram Bot
yankovskiid/Telegram_weather_bot pull request #1
Opened 2017-07-09 18:24 UTC by yankovskiid

2017-07-09 18:25 UTC, yankovskiid commented
@anatoliliotych please review code

2017-07-09 18:29 UTC, anatoliliotych requested changes

2017-07-09 18:29 UTC, anatoliliotych commented on Telegram_bot-master/bot.rb
> +binding.pry
it shouldn't be here

2017-07-09 18:29 UTC, anatoliliotych commented on Telegram_bot-master/bot.rb
> +require_relative 'token.rb'
use .env file with dotenv gem for storing token

2017-07-09 18:29 UTC, anatoliliotych commented on Telegram_bot-master/bot.rb
> +  req = OpenWeather::Current.city(city, options)
what if this request fail? you should think about such things working with third party services!

2017-07-09 18:29 UTC, anatoliliotych commented on Telegram_bot-master/commands.rb
> +
empty line should be removed!

2017-07-09 18:29 UTC, anatoliliotych commented on Telegram_bot-master/commands.rb
> +HELP_COMMANDS = " /help - commands list \n /weather_current - waether forecast \n /mem - memos /n".freeze
you can store strings in yml file

2017-07-10 08:51 UTC, yankovskiid commented
@anatoliliotych please review code again

2017-10-22 20:43 UTC, merged